version: '3'

services:

    app:
        build: .
        container_name: app
        volumes:
            #- .:/var/www
            # usando Docker Toolbox só funcionou com o nome do volume com / na frente, no caso é /laravel
            - /codemicrovideos:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        #entrypoint: dockerize -template ./.docker/app/nginx.conf:./.docker/nginx/nginx.conf
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            #- .:/var/www
            # usando Docker Toolbox só funcionou com o nome do volume com / na frente, no caso é /laravel
            - /codemicrovideos:/var/www
        networks:
            - app-network
        depends_on:
            - app
        #environment:
        #    - NGINX_HOST=app
        #    - NGINX_HOST=9000

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            #- .:/var/lib/mysql
            # usando Docker Toolbox só funcionou com o nome do volume com / na frente, no caso é /dbdata
            - /codemicrovideosdb:/var/lib/mysql
            #- ./.docker/mysql:/docker-entrypoint-initdb.d
            - /codemicrovideosmysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
